### ISSUE TITLE
[Question] Realtime CSG optimization for large structures?

### ISSUE THREAD

**Issue by CodeCaster28** [LogicalError/realtime-CSG-for-unity#147]
First thing I want to ask is how optimal is Realtime CSG when running a scene with large constructions e.g. made with ~1500 brushes. If someone tested it I would be happy to know I can safely start making my level. Second question is about scene loading time. I've been working with other CSG tool for unity, unfortunately just about ~1000 brushes make loading a scene takes about 20 seconds, before it took 4 seconds..

**Comment by LogicalError** [comment]
Hi @CodeCaster28 !

Since performance is determined by how many brushes are modified at the same time, per model, it helps a bit to simply divide your level into multiple models. This is something you'd want to do anyway because a model will turn into a mesh at run-time If the run-time meshes are smaller (in dimensions), then it's easier for Unity to not render parts of your level that are not visible.. if you have just one humongous mesh, your entire level will be rendered every frame..

That said, take a look at this older (pre-release) video https://www.youtube.com/watch?v=Yt0gP4FVhAc 
It's a half-life black mesa level imported into realtime-CSG. 
It has >3000 brushes _in a single model_ and works just fine!
I don't remember the loading times though ..

And, of course, if you ever run into any kinds of performance or non-performance issues, just sent me a the level so I can see what the problem is :)

**Comment by otdavies** [comment]
From my experience, real-time CSG will run absolutely gloriously in pretty much every situation. I can vouch for that. Just a side note though, when working on the level don't set to static if you're actively editing it. If you do, it will slow down to a crawl due to Unity's optimizations ruining real-time CSGs excellent n*log(n) optimizations of brush spatial locality! (Unity's fault, not LogicalErrors)

**Comment by LogicalError** [comment]
@otdavies that probably has to do with Unity updating lighting information (realtime & lightmap lighting stuff) every time a static mesh has been changed

**Comment by LogicalError** [comment]
If someone can provide me a test map to work on, that is complex enough to cause performance issues when static I can take a look and see if I work around Unity's performance issues there

**Comment by otdavies** [comment]
Sure, I'll do that later! I didn't mean it in a negative way. I often have dealt with Unity's automatic static mesh combining behind the scenes. I have noticed it to slow down some of the "smooth" dragging effect, it still works effectively of course. Unity just treats more models as a collective glob when they are static, meaning the bound boxes get bigger, meaning the accuracy of knowing what shapes overlap becomes slower, etc. It is has nothing to do with your excellent plugin! All of Unity's stealthy background wizardry. I'll send you my test scene at some point.

**Comment by LogicalError** [comment]
cool, thanks :)

**Comment by CodeCaster28** [comment]
Thank you for your comprehensive answers. I'll divide levels into parts so I can use advantages of occlusion culling, I just get used to bsp-based engines where optimization were a tough work. Since CSG are turned into meshes in unity it indeed should not be a problem with optimization. Also I'm already surprised how I can slice and subtract multiple curved brushes without generating bad faces or producing lags. Your algorithm is revolutionary!

**Comment by otdavies** [comment]
So true! Revolutionary is the word! Take a look at LogicalError's website sometime and read through how it is done, it is fascinating! Huge respect for his algorithm and his incredible implementation, I haven't felt so at home working on in engine models in a very long time.

**Comment by LogicalError** [comment]
Come on guys, you're making me blush! :)

**Comment by ianmasters** [comment]
Maybe this has been mentioned elsewhere but perhaps some kind of per-object / per-scene slicing option where you could set up XYZ dimensions to cut models into different GameObjects at runtime/build time to automatically subdivide large static models into a hierarchy of sub objects for optimised culling could be useful?
Could also possibly add a manual slice option to the toolbar/menu so you can do this manually?

**Comment by LogicalError** [comment]
Hi @ianmasters , thanks for the suggestion, that sounds useful, I'll look into it, thanks :)
