### ISSUE TITLE
BakedGI Clustering and RealtimeCSG

### ISSUE THREAD

**Issue by Drexen** [LogicalError/realtime-CSG-for-unity#164]
![realtimecsg_clustering](https://cloud.githubusercontent.com/assets/22818547/22294891/ec00fae0-e30c-11e6-96e2-053f182d1bb5.png)

Using BakedGI with a single complex CSGModel causes Clustering to compile for ever. The smaller complex geometry highlighted in the image compile in just a few seconds. It feels like it would get very tedious having to manually split my geometry into multiple sub-CSGModels. How do you intend larger levels to be constructed using RealtimeCSG. Also how was your Half-Life level split up into CSGModels?

**Comment by LogicalError** [comment]
The problem with GI is that it decides what part of the lightmap is used for each triangle, if I modify the mesh, it'll completely redo that every time. I'm not sure if there is anything I can do about it, it's a Unity limitation. As for splitting things into multiple CSG models, you'd want to do that anyway since one giant mesh for your entire level means that you'll constantly be rendering larges parts of your scene all the time, even if it's invisible. More models means that Unity will be able to cull large parts of your level and rendering will be much faster. The Half-Life was one big CSG-Model, it wasn't split up.

**Comment by LogicalError** [comment]
This might help you with speeding up the lighting calculations https://unity3d.com/learn/tutorials/topics/graphics/summary-precomputed-realtime-gi?playlist=17102

**Comment by Drexen** [comment]
This is more my lack of knowledge of lighting in unity but is there a way to get ambient occlusion without using Baked GI?

**Comment by LogicalError** [comment]
Not that I know of, only screenspace ambient occlusion post processing shaders as afar as I know
