### ISSUE TITLE
UV changes unexpectedly when selecting a single face

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#188]
"I have an issue where after smearing across several faces, if I then try to select a single face, the UV changes unexpectedly (offsets change, rotates by 90 degrees, and it seems to do this consistently to the same offset/rotation).
I'm around 90% sure this happens when a face has been extruded instead of generated."

see https://prenominal.nl/forum3/showthread.php?tid=79&pid=191#pid191

**Comment by Petethegoat** [comment]
Repro for Unity 5.6.2f1:

1) new 3d project
2) import 1.410 from the assetstore. I imported everything except the demo folder.
3) use box generator to create a wall. mine was roughly 7 * 3 * 1, but presumably this doesn't matter. i set grid snap to 1m but presumably that's also unimportant
4) extrude to continue the wall. i extruded again from the first extrusion to create 3 sections.s
5) modify the UVs in any way- by dragging in scene view, rotating from the surfaces menu, smearing with g
6) click ANY of the surfaces you've just modified. they should reset to whatever UV they had originally.

interesting it seems like some state is saved, because if you double or half the scale a few times, and then click the surface to repro the bug, trying to modify the scale again will use the modified scale instead of the bugged original UV that's shown on the surface. (If that isn't clear let me know and I will take more time to explain it properly.)

**Comment by Petethegoat** [comment]
to expand on the last paragraph, the whole intended UV is saved, which you can see by halving scale, single clicking once to reproduce the bug, and then rotating or offsetting. it seems to just be a display issue.

after you have bug-reset the UVs, they persist when you go into play mode, but reset to the correct UVs upon exiting play mode.

**Comment by Petethegoat** [comment]
also, this seems to happen on any face, not just extruded ones! It also happens on some but not all faces on a generated sphere. I'll let you know if I find any method to the madness.

**Comment by LogicalError** [comment]
Thanks, that'll help me narrow this down :)

**Comment by Petethegoat** [comment]
https://forum.unity.com/threads/released-realtime-csg-level-design-for-unity.427601/page-5#post-3305286

New repro with video too :)

**Comment by LogicalError** [comment]
fixed in 1.507!
