### ISSUE TITLE
Runtime support

### ISSUE THREAD

**Issue by LogicalError** [LogicalError/realtime-CSG-for-unity#191]
Loads of people asking for this.

Current plan: 

- improve editor API as a testbed for the runtime API
- release windows and mac version for runtime

**Comment by cmdr2** [comment]
Hi Sander, I'm taking a look at this, with the hope that it's a reasonable amount of effort for someone unfamiliar with the codebase like me :) I really need runtime for my project, and RealtimeCSG perfectly fits the tasks I need vs ProBuilder etc.

If you recommend using RadicalCSG instead, I'd be happy to adopt it and work out the bugs with you (since it's not production-ready yet). My project will be early-access, so I'll be testing it a lot and a degree of bugginess is okay for now.

In the meantime, I'm reading through the code now to map it out.

If updating this project is the way to go, I'd really appreciate any code pointers (off the top-of-your-head) about the quickest way to get this working in the runtime. The functionalities I plan to support at runtime are:
a) Given a set of Vector3 points, create a 2D shape
b) Given a 2D shape and a distance along the normal, extrude to a 3D shape (I suppose: a set of 3D convex brushes). // I want to mimic the ability to interactively display the extrude while moving along the normal, similar to the editor
c) Given a Ray, find the projected Vector3 point (and its linked surface) on the model // to be able to draw a new 2D shape on a surface, by projecting the points
d) Given a new set of Vector3 points on the surface of a model, create a new 2D shape
e) Extrude or inset the new 2D shape over the existing model
f) Given a Ray, find the projected surface // to be able to select a surface to edit from the model
g) Given a surface in the model, extrude it along a normal

Is the core algorithm that supports the above scenarios dependent on UnityEditor APIs? Looking at #155, is the issue broadly about splitting it across frames and runtime path updates (what's that?)? Or are there deeper code-level dependencies on being in the editor (I see a lot of stuff inside #if UNITY_EDITOR blocks)?

Thanks a lot, and cheers :)
~cmdr2

**Comment by LogicalError** [comment]
Hi @cmdr2 , 
With RadicalCSG I assume you mean Chisel?
Anyway, Realtime CSG is essentially on life support since most of my efforts are currently going towards Chisel, which will become the successor of Realtime CSG. There will also be an upgrade path from Realtime-CSG to Chisel
And yes, it's not yet production ready. If you have questions I suggest you go to the Chisel discord https://discord.gg/zttNkPQ
The biggest problem with Realtime CSG not supporting runtime has to do with it's dependency on native code

**Comment by cmdr2** [comment]
Thanks! :) Coming back to this thread, is the native code checked in
anywhere? I apologise if I missed it, but all I found was the DLL and osx
native object.
