### ISSUE TITLE
Linux .DLL/.SO Support

### ISSUE THREAD

**Issue by Phobos001** [LogicalError/realtime-CSG-for-unity#200]
Hello! I am using Linux for development, and I want to use RealtimeCSG in the linux editor. It seems the DLL is not supported, leading to DllNotFoundException's. I don't know how portable the code is, and I know it can be hard to port something to another OS, but this would be really awesome to have, so I don't have to boot into Windows to use Unity there. Thank you very much!

**Comment by LogicalError** [comment]
Hi, unfortunately the more platforms I need to support, the harder things are for me since my time is limited. 

It's already a chore to support both windows and mac os. 

For Linux I don't even have a machine to boot, compile and test on .. and I'm sorry to say that so far, in the 2 years I've been working on this, you've been the only person to ask about it. 
So I hope you understand that it doesn't make sense for me to put my time and effort into supporting Linux, compared to all the other things I could do for Realtime CSG :-(
Sorry :-(

That said, at some point I might move the internal CSG code to C#, which may happen for a variety of reasons, which would automatically make it work on Linux as well. I have no time table for that however

**Comment by Phobos001** [comment]
It's okay, I totally understand the time thing; I'm basically working 14
hour shifts with taking care of my severly autistic brother (Who needs 24/7
supervision), my mom, and my grandma. Game development in my current
situation is a luxury. No hard feelings dude ;)

I can dual boot into windows, but too many times I've lost a lot of work
from random resets and bluescreens, and time lost trying to diagnose what
went wrong to begin with. So I can use it on windows, but its much slower.

Either way, your tool is amazing and I'm glad I could help fund it's
continuous development. You're awesome dude, keep it up 🙂

**Comment by LogicalError** [comment]
Thanks for understanding :)
