### ISSUE TITLE
Realtime CSG cannot be removed from project completely in Unity, requiring manual removal with Unity closed

### ISSUE THREAD

**Issue by Candescence** [LogicalError/realtime-CSG-for-unity#259]
I've discovered that deleting the Realtime CSG folder inside Unity actually causes Unity to attempt to reimport parts of the plugin, requiring a full manual removal with Unity closed.

Discovered in Unity 2018.1.0f2.

**Comment by LogicalError** [comment]
I'll take a look

**Comment by LogicalError** [comment]
Sorry, I've been busy lately so I haven't had time to look at this yet

I don't know how Unity could "reimport" Realtime-CSG? Realtime-CSG is certainly not doing that ..

There is a .dll in the realtime-CSG folder that is used by Unity and can't be deleted because of that.
There is nothing I can do about that, it's actually an issue because it also makes it impossible to for me to update that dll while unity is running (that's why these .dlls have an unique name per version)

**Comment by FaffyWaffles** [comment]
I'm having this same issue, what would be the procedure to remove it from the project then?

**Comment by Kerfuffles** [comment]
If you have installed RealtimeCSG as a UPM package (I'm working on fixing this, it'll be included in #349, the issue being #356 ), then:
1) Open the folder location of RealtimeCSG from the `project window > (Packages if UPM, Assets otherwise)  > Right-Click RealtimeCSG > Show in Explorer`
2) (If UPM) Remove RealtimeCSG from the package manager
3) Close Unity, and delete the RealtimeCSG folder from the explorer window you opened in the first step.
4) Download the latest release of RealtimeCSG from the releases page, and extract the RealtimeCSG folder to anywhere in your project > Assets folder
5) Open your project and wait for unity to compile scripts

It is *very* important you do not open your project until you have completed steps 2 to 4. Repeat steps 3 to 5 when updating to a new version. To only remove RealtimeCSG, then follow only steps 1 to 3.

It's an issue with Unity as far back as I can remember, and I really wish they would fix it. Unfortunately there still isn't a way to get around this, and it doesn't look like it's a priority issue for the Unity team to fix.
