### ISSUE TITLE
[Request] Generate mode - points placement behaviour

### ISSUE THREAD

**Issue by MarisaLovesUsAll** [LogicalError/realtime-CSG-for-unity#27]
Something strange is going on with these points. Take a look:

![bug2](https://cloud.githubusercontent.com/assets/5061652/19419062/3c77efda-93d8-11e6-97b0-7bff619222ab.gif)
![bug3](https://cloud.githubusercontent.com/assets/5061652/19419063/3c9ffd04-93d8-11e6-885d-59050eda46c4.gif)

Scene View size is not important, bug present with any size.

Unity version: 5.4.1f1 Personal
Windows 10, display 2560x1440 with 100% scaling, CPU: Intel i7 4770k, GPU: Intel 4600 HD.

**Comment by LogicalError** [comment]
Hmm, yeah in this case it's a mathematical thing that I don't know a good solution for.
The problem is that your mouse is on an infinite plane going into the distance, and it's possible to move your mouse in a position that will never intersect that plane .. even if it could, it would be infinitely large :-/

**Comment by LogicalError** [comment]
I guess a solution might be to show the grid for the plane you're working  on .. then it's visually clear what's happening

**Comment by LogicalError** [comment]
No wait ... the grid already should be showing? Have you changed the color of the grid or background?

**Comment by MarisaLovesUsAll** [comment]
Skybox colour was too white to see the rulers. Here, some more gifs

![bug](https://cloud.githubusercontent.com/assets/5061652/19455553/0c8f3906-94c6-11e6-839c-4c42983c58bc.gif)
![bug2](https://cloud.githubusercontent.com/assets/5061652/19455625/67feada8-94c6-11e6-8b99-e20bd6cc196f.gif)

With box draw, this seems to be a legit behaviour.

But I used free draw. My case was to draw a panel to my ladder:
![bug3](https://cloud.githubusercontent.com/assets/5061652/19455703/bac48e72-94c6-11e6-9f3c-03d45ce9cae1.gif)
Looks like free draw is somewhat axis-aligned, just like box draw, which causes the bug:
![bug4](https://cloud.githubusercontent.com/assets/5061652/19455753/f5584d76-94c6-11e6-9edc-0947a4cb6899.gif)
Is the surface normal of starting point important to algorithm?

**Comment by LogicalError** [comment]
I just got back from vacation. I'll look at your issue tomorrow

**Comment by LogicalError** [comment]
I didn't manage to take a stab at this today, I'll try again tomorrow, sorry.

**Comment by LogicalError** [comment]
There is no easy solution to this, because you want different behavior in different situations and it's almost impossible to figure out the intention of the user. Right now the code assumes that you want to work aligned with the surface you start on. I don't have a good solution for this just yet, I need to think about this.
