### ISSUE TITLE
Is this project abandoned in favor of chisel?

### ISSUE THREAD

**Issue by ssoher** [LogicalError/realtime-CSG-for-unity#329]
I'm weighing my options for production, trying out the limited set of CSG tools for Unity out there. It seems that both SabreCSG and realtimeCSG are not receiving any updates anymore. There is also Chisel that's a WIP but it seems the progress has been slow on that as well and it's some ways away to be production ready.

So is this a good option for production atm? Or abandoned?

**Comment by Kerfuffles** [comment]
None of the projects are abandoned. Focus is more on chisel, and SabreCSG and RCSG is getting fixes for breaking unity API changes, or bugs/regressions. I just recently did some work to make RCSG compatible with 2021.2+, and @Henry00IS has been helping keep SabreCSG updated, which should also now support 2021.2+. RCSG is perfectly fine for production and is the recommended option.

Were just slow on updates because were doing this in our free time.

Apologies for such the long delay in response. We are much more active on discord, if you needed help or more immediate feedback on something.
