### ISSUE TITLE
Bugs when creating small cylinders

### ISSUE THREAD

**Issue by killerlegs** [LogicalError/realtime-CSG-for-unity#337]
- You have to use a very low number of sides, otherwise it won't generate (gizmo becomes red)
- Sides are not equal. The point placement on the circle is probably off by one.
- As soon as you try to move the side, it explodes and becomes a box.

https://user-images.githubusercontent.com/32152103/155892250-92623929-bf6a-404a-aec7-898072568141.mp4

**Comment by LogicalError** [comment]
I suspect this is due to the vertices being merged when the cylinder is this small .. more sides mean the vertices are closer together
The vertex merging is .. problematic code.

**Comment by Kerfuffles** [comment]
Closing this, as work on algorithm stuff is having focus directed towards Chisel. I'll be providing help with breaking or minor bug fixes due to Unity updates. Once the more glaring issues with RCSG are fixes, I will then, myself, be focusing on work on Chisel.

For the time being, it is encouraged to make smaller meshes in an external modeling package, or to reduce the number of sides in a brush to avoid this problem.
