### ISSUE TITLE
Video tutorial

### ISSUE THREAD

**Issue by eagleeyez71** [LogicalError/realtime-CSG-for-unity#63]
Here is a basic tutorial what I did for anyone just getting started.
It is not really a tutorial in such,  just me showing some features off of Realtime CSG.  I hope it helps some of you.

https://youtu.be/TUkKNoIQ1bk

**Comment by sonygod** [comment]
nice!

**Comment by LogicalError** [comment]
thanks @eagleeyez71 !

I noticed a couple of things:

- There is actually a second video here https://www.youtube.com/watch?v=e0yF7m6AWek , not sure if you knew that since you said that the video was too quick .. I assume you mean the first (although the second might also be too fast?)  .. you can actually see it in your video on the asset store page

- The github tickets serve 'sort of' as a forum at the moment, but I suppose it does make more sense to have a real forum ...

- I hear you on the hotkeys ... I'll see if I can make them configurable somehow .. the placement of the hotkeys was done to make them easily reachable for the left hand, assuming that the right hand will be holding the mouse. Unfortunately a lot of keys are also used by Unity, which reduces the number of keys available greatly. 

- I guess I should show on screen better in what shape edit mode you are (box/free-draw/cylinder) so when you press the wrong key you see it immediately ..

- Pressing Alt turns on the unity orbit camera, I'll try to see if I can prevent it from zooming in until actually moving the camera around the object though ..

- the grid colors are taken from the standard unity colors at the moment, and can be changed in preferences/colors ... but you're right, the standard unity grid colors are very hard to see, so different colors should be used ..

- the brush disappearing, which is visible in the start of the video, is fixed in a later version than is available on the asset store. Unfortunately sometimes it takes *a long* time before updates are accepted to the asset store, and if I update an update it goes to the back of the queue ... so the asset store is quite a bit behind. There are updates available on http://prenominal.nl/updates/index.php that are up to date.

- seeing you sizing the brush in a direction that's disabled (the X/Y/Z) makes me think that I should warn the user when that's happening .. so I'll look into that.

- I agree that disabled X/Y/Z should be way more visible

- The rotating of the brush not working in 2D view might be because of the 2D camera being too much forward or backward (you can move it forward/backward with W and S, which is why sometimes stuff is not visible in the 2D view) .. regardless, this is still a bug and I need to fix it

- With surfaces, the G key also work by clicking on one surface and then click on another surface .. which makes it easier if you want to copy a material between non connected surfaces

- It's pretty clear that being in Surface mode can be confusing when you don't realize in Surface mode, so I need to have a way to make it more obvious that you're in surface mode ..

-  Releasing the V key should finish a 2D shape, that it doesn't is a bug ..

- Materials not properly set when exporting to fbx is a bug too, you didn't do anything wrong ..

- The 'not being able to select things' at the end of the video was because you where in surface mode, it wouldn't have happened in other edit modes, still a bug though

- clip mode only works when you select a brush. You can actually select/deselect brushes after you created your clip plane. You can clip multiple brushes at the same time for instance. This needs to be shown more clearly obviously ... 


Finally, thanks for making this tutorial! :) .. It's a shame that you ran into so many issues though :(
I'll see if I can fix those ASAP

(and thanks for giving me invaluable feedback by making this video!)

**Comment by LogicalError** [comment]
I've made a bunch of tickets to fix all the issues I noticed in the video, thanks again!

**Comment by LogicalError** [comment]
@eagleeyez71 I just created a forum! https://prenominal.nl/forum/
